storage_proxy: propagate overloaded_exception to the client
CQL has a specialized OVERLOADED exception type, which drivers
can interpret and apply their own retry policies. When a request
is refused due to too high read concurrency, it's now propagated
as an OverloadedException.
Example from cassandra-stress logs:
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.OverloadedException: Queried host (localhost/127.0.0.1:9042) was overloaded: Endpoint 127.0.0.1 is overloaded (keyspace1.standard1)))